### ISSUE TITLE
Add `offset` as keyword

### ISSUE THREAD

**Issue by juliusv** [celian-garcia/monaco-languages-promql#2]
Currently support for completion and highlighting for `offset` is missing:

* `foo offset 7d`
* `foo[5m] offset 7d`

This should probably be added as a keyword?

**Comment by celian-garcia** [comment]
Hi Julius !
I am sorry, the watching was not activated, I don't know why ! Now I activated it.

I will have a look it's probably not complex.

Thanks for the issue !

**Comment by juliusv** [comment]
Thanks :)
